# Chap 3 介紹張量(Tensor)

Tensor 是用來表示向量、矩陣或其他維度資料的一種資料結構及容器。
如何得知張量的維度（amount of axis）？ 可尤其索引值的 **個數** 得知。

## Session 3.1 浮點數的世界

## Session 3.2 Tensor: 多維陣列

In [10]:
'''
以下在比較array 跟tensor
'''
a=[1.0,2.0,1.0]
print(a[0])
a[0]=3.0
print(a)

1.0
[3.0, 2.0, 1.0]


In [6]:
import torch
a=torch.ones(3) #創造一個3維的1軸向量，其元素為1
print(a)
print(a[1])
print(float(a[1]))

tensor([1., 1., 1.])
tensor(1.)
1.0


In [7]:
a[2]=2.0
a

tensor([1., 1., 2.])

In [15]:
points=torch.zeros(6)
points[0]=4.0
points[1]=1.0
points[2]=5.0
points[3]=3.0
points[4]=2.0
points[5]=1.0
points

#與以下等價
points2=torch.tensor([4.0,1.0,5.0,3.0,2.0,1.0])
points2

#提取A座標
float(points[0]),float(points[1])

(4.0, 1.0)

In [17]:
## 創造2軸張量
points=torch.tensor([[4.0,1.0],[5.0,3.0],[2.0,1.0]])
points[0]

tensor([4., 1.])

In [ ]:
points.shape
#代表points是一個2軸張量（第0軸有3維，第1軸有2維），.shape用來回傳每個軸的維度

torch.Size([3, 2])

In [20]:
points=torch.zeros(3,2)
points #透過指定shape來建立tensor

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [21]:
#提取2軸tensor的個別元素（by 2 index）
points=torch.tensor([[4.0,1.0],[5.0,3.0],[2.0,1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [22]:
points[0,1]

tensor(1.)

In [ ]:
points[0] #此結果為一個大小為2的1軸張量

tensor([4., 1.])

## Session 3.3 利用索引值操作張量

本節要介紹**範圍式索引法**（用於提取tensor中，一定範圍的元素），類似python list操作方法。<br>
**進階索引**(另一種強大的索引方式)將在chapter4中提到。

In [24]:
some_list =list(range(6)) #產生一個從0到5的數字串列
some_list[:]              #提取串列中所有元素

[0, 1, 2, 3, 4, 5]

In [ ]:
## Python list寫法
some_list[0:4] #提取no.0~no.3個元素
some_list[1:] #提取no.1~最後一個元素
some_list[:4] #提取no.0~no.3個元素
some_list[:-1] #提取no.0~倒數第二個元素
some_list[1:4:2] #提取no.1~no.3個元素，每次間隔2個元素

[1, 3]

In [27]:
## 對tensor使用範圍式索引法
points=torch.tensor([[4.0,1.0],[5.0,3.0],[2.0,1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [28]:
points[1:,:]

tensor([[5., 3.],
        [2., 1.]])

In [29]:
points[1:,0]

tensor([5., 2.])

## Session 3.4 為張量命名

利用names參數替每個軸命名（typr: string）

In [ ]:
import torch
weights_named=torch.tensor([0.2126, 0.7152,0.0722], names=["channels"])
weights_named
#refine_names()重設名稱

/var/folders/yb/xnfk9z6x34527z3924bcjqcr0000gn/T/ipykernel_25316/3701717441.py:2: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/c10/core/TensorImpl.h:1974.)
  weights_named=torch.tensor([0.2126, 0.7152,0.0722], names=["channels"])


tensor([0.2126, 0.7152, 0.0722], names=('channels',))

In [3]:
img_t = torch.randn(3,5,5) #創造一個3軸的張量
batch_t = torch.randn(2,3,5,5) #創造一個4軸的張量
img_named = img_t.refine_names(..., 'channels','rows','columns') ## ...表示忽略前面，只幫最後三軸命名
batch_named = batch_t.refine_names(...,'channels','rows','columns')
print("img_named:" , img_t.shape, img_named.names)
print("batch_named:" , batch_t.shape, batch_named.names)

img_named: torch.Size([3, 5, 5]) ('channels', 'rows', 'columns')
batch_named: torch.Size([2, 3, 5, 5]) (None, 'channels', 'rows', 'columns')


In [ ]:
#align_as()將weights_named內tensor的軸按照img_named順序進行排序，（會自動添加缺失的軸）
weights_aligned = weights_named.align_as(img_named) #weights_named為一軸張量
weights_aligned.shape, weights_aligned.names
#weights_aligned


(torch.Size([3, 1, 1]), ('channels', 'rows', 'columns'))

In [8]:
img_named

tensor([[[ 0.7549,  0.7040, -0.5905, -1.4944, -1.1411],
         [ 1.4837, -1.6251, -0.1032, -0.1640,  0.7529],
         [-0.1131, -1.6989, -0.8747, -0.0028,  0.8432],
         [ 0.4779, -0.1079,  0.1461, -1.2731,  0.2933],
         [-0.3215,  0.4853,  1.3529,  1.3185, -1.0132]],

        [[ 1.3211, -0.2918,  1.5793,  0.3865,  0.9758],
         [ 1.0859,  0.0506, -1.6146,  0.9141, -0.7674],
         [-0.5162, -1.6761, -1.5684, -0.2508, -0.4115],
         [-1.4717, -0.5339, -0.6223, -0.0428,  0.2181],
         [-0.6115,  1.6622, -0.1560, -0.6525,  0.9141]],

        [[-0.0164, -0.0712,  0.6364,  0.5131,  0.7174],
         [-0.9668,  0.2966, -0.9905,  0.1763, -0.3980],
         [-0.5453,  0.2671,  0.8572, -0.0907,  1.0738],
         [-1.9566, -0.0190, -0.1056,  1.5258,  0.5857],
         [ 1.6976, -0.5259, -0.7849, -0.4168, -0.2698]]],
       names=('channels', 'rows', 'columns'))

In [9]:
weights_aligned

tensor([[[0.2126]],

        [[0.7152]],

        [[0.0722]]], names=('channels', 'rows', 'columns'))

In [7]:
gray_named = (img_named * weights_aligned).sum("channels")
gray_named.shape, gray_named.names

(torch.Size([5, 5]), ('rows', 'columns'))

In [10]:
gray_named

tensor([[ 1.1042, -0.0642,  1.0499, -0.0042,  0.5071],
        [ 1.0223, -0.2879, -1.2482,  0.6316, -0.4175],
        [-0.4326, -1.5407, -1.2458, -0.1865, -0.0375],
        [-1.0922, -0.4061, -0.4216, -0.1911,  0.2606],
        [-0.3831,  1.2540,  0.1194, -0.2165,  0.4189]],
       names=('rows', 'columns'))

In [ ]:
## 有些函式不支援以張量維度名字來操作，重新命名為none
gray_plain = gray_named.rename(None)
gray_plain.shape, gray_plain.names

(torch.Size([5, 5]), (None, None))

In [12]:
batch_t

tensor([[[[ 2.7065e+00, -5.5704e-01, -4.9430e-01, -1.6597e+00, -1.6428e-01],
          [-1.6635e+00,  2.2162e+00,  1.4492e+00,  6.9233e-01, -2.1413e+00],
          [ 5.5001e-01,  4.7237e-01, -1.1933e+00,  2.0680e-01,  1.1445e-01],
          [-8.4152e-01, -8.5186e-01, -7.5899e-01, -1.3911e+00, -1.4730e+00],
          [-2.1075e+00, -1.4854e+00,  2.0674e-01, -5.2526e-02,  7.1932e-01]],

         [[ 2.0777e+00, -1.8098e+00, -1.1774e+00, -3.6178e-01, -1.2633e+00],
          [-1.9797e-01,  4.9894e-01, -4.5753e-01,  1.0394e+00, -5.3807e-01],
          [ 1.7010e+00, -1.4255e-01,  3.9891e-01,  4.2940e-01, -4.4490e-01],
          [ 4.7264e-01, -6.0318e-01,  1.1535e+00, -4.2577e-01, -8.8096e-01],
          [ 8.3530e-02, -4.1871e-01, -1.2150e+00,  4.2279e-01,  8.7528e-02]],

         [[-1.3803e-01,  1.3739e+00,  1.8652e-01,  1.3582e+00, -1.8262e-01],
          [-6.5369e-01, -5.2667e-01,  1.0765e-01, -1.4555e-01,  5.1576e-01],
          [-7.6005e-01, -7.9129e-02, -1.6418e+00,  1.6774e-03, -1.2493e+

## Session 3.5 張量的元素型別

tensor預設資料類別是32位元的單精度浮點數
GPU才支援16位元的半精度浮點數

In [10]:
#在創建張量時就設定其資料型態
import torch
double_points = torch.ones( 10, 2, dtype=torch.double) #float64
short_points = torch.tensor([[1,2], [3,4]], dtype=torch.short) #int16
double_points
short_points 

tensor([[1, 2],
        [3, 4]], dtype=torch.int16)

In [8]:
short_points.dtype

torch.int16

In [ ]:
#寫法2
double_points = torch.zeros(10,2).double()
short_points = torch.ones(10,2).short()
print(double_points.dtype)
print(short_points.dtype)

#寫法3  to()會檢查張量原本的數值型類別與我們要求的是否一致 to()還可以接受其他參數
double_points = torch.zeros(10,2).to(torch.double)
short_points = torch.ones(10,2).to(torch.short)
print(double_points.dtype)
print(short_points.dtype)

torch.float64
torch.int16


In [14]:
points_64 = torch.zeros(5,dtype=torch.double)

points_short = points_64.to(torch.short)
points_64 * points_short
#64          #16

tensor([0., 0., 0., 0., 0.], dtype=torch.float64)

## Session 3.6 其他常用的張量功能

In [15]:
a = torch.ones(3,2)
a_t = torch.transpose(a,0,1)
a.shape, a_t.shape

(torch.Size([3, 2]), torch.Size([2, 3]))

In [ ]:
a = torch.ones(3,2) 
a_t = a.transpose(0,1)
      #使用tensor的method(API)
a.shape, a_t.shape

(torch.Size([3, 2]), torch.Size([2, 3]))

## Session 3.7 張量的儲存原理

In [ ]:
#對storage 進行索引，不能用兩個索引直來索引storage（永遠為1軸）
points = torch.tensor([[4.0,1.0],[5.0,3.0],[2.0,1.0]])
#創3xpoints.storage()2 的2軸張量，用來存放3個座標點
 ##查看points張量的storage

 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]

In [ ]:
points_storage = points.storage()
points_storage[0]
points.storage()[0]

4.0

In [26]:
#當我們改變storage的值時，相應的tensor也會一起改變
points = torch.tensor([[4.0,1.0], [5.0,3.0], [2.0,1.0]])
points_storage = points.storage()
points_storage[0] = 2
points

tensor([[2., 1.],
        [5., 3.],
        [2., 1.]])

In [29]:
#使用in-place方法來修改數值：zeros_(), abs_(), sqrt_()
a = torch.zeros(3,2)
a

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [ ]:
#不是複製一份原始資料！！！是直接對張量做處理
a.zero_()
a

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

## Session 3.8 大小(size)、偏移(offset)及步長(stride)

* size(在numpy中稱作shape)表示每個軸上有多少元素<br>
* offset是張量首個元素在storage中的索引值（預設為0）<br>
* stride(為tuple——有序、不可變動的資料結構)為提取各軸下一個元素時，需要跳過的元素數量<br>
* 要知道索引為(i,j)的元素在storage的索引值，可透過 **storage_offset+stride[0]\*i +stride[1]\*j**

In [30]:
points=torch.tensor([[4.0,1.0],[5.0,3.0],[2.0,2.0]])
points.storage()

 4.0
 1.0
 5.0
 3.0
 2.0
 2.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]

In [ ]:
secoond_point = points[1]
secoond_point.storage() # 可以發現與points張量指向統一個storage

 4.0
 1.0
 5.0
 3.0
 2.0
 2.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]

In [ ]:
secoond_point.storage_offset()
## 由於跳過4.0, 1.0兩個元素，故offset=2

2

In [40]:
secoond_point.size()
secoond_point.shape

torch.Size([2])

In [42]:
points.stride()

(2, 1)

In [ ]:
secoond_point = points[1]
secoond_point.size()

tensor([5., 3.])

In [49]:
#因為輸出points second_point張量的storage為一致的，所以修改second_point的值，points的值也會被修改！
points = torch.tensor([[4.0,1.0],[5.0,3.0],[2.0,1.0]])
second_point = points[1]
#second_point = points[1].clone()
## 解法：為了避免修改到母tensor的值，我們可以利用clone()將母張量所需的元素複製出來使用
print(second_point)
second_point[0]=10.0
points

tensor([5., 3.])


tensor([[ 4.,  1.],
        [10.,  3.],
        [ 2.,  1.]])

In [ ]:
## transpose(把原本張量的stride元素對調，進而產生一個新tensor，不會佔用新的記憶體空間) of tensor
points = torch.tensor([[4.0,1.0],[5.0,3.0],[2.0,1.0]])
print(points)
points_t=points.t()
points_t

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])


tensor([[4., 5., 2.],
        [1., 3., 1.]])

In [53]:
#check 2 tensor share common storage or not
print(id(points.storage()) == id(points_t.storage()))
#shape equal ??
print(points.stride())
print(points_t.stride())

False
(2, 1)
(1, 2)


In [ ]:
## 多軸張量的transpose
some_t =torch.ones(3,4,5)
#some_t = torch.arange(1, 61).reshape(3, 4, 5)
print(some_t)
print(some_t.shape)
transpose_t = some_t.transpose(0,2) #第0軸第2軸進行轉置
print(transpose_t.shape)

torch.Size([3, 4, 5])
torch.Size([5, 4, 3])


In [ ]:
print(some_t)
transpose_t = some_t.transpose(0,2) #第0軸第2軸進行轉置
print(transpose_t)
print(some_t.stride(), transpose_t.stride())
print("可以發現stride值對調了")

tensor([[[ 1, 21, 41],
         [ 6, 26, 46],
         [11, 31, 51],
         [16, 36, 56]],

        [[ 2, 22, 42],
         [ 7, 27, 47],
         [12, 32, 52],
         [17, 37, 57]],

        [[ 3, 23, 43],
         [ 8, 28, 48],
         [13, 33, 53],
         [18, 38, 58]],

        [[ 4, 24, 44],
         [ 9, 29, 49],
         [14, 34, 54],
         [19, 39, 59]],

        [[ 5, 25, 45],
         [10, 30, 50],
         [15, 35, 55],
         [20, 40, 60]]])
tensor([[[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10],
         [11, 12, 13, 14, 15],
         [16, 17, 18, 19, 20]],

        [[21, 22, 23, 24, 25],
         [26, 27, 28, 29, 30],
         [31, 32, 33, 34, 35],
         [36, 37, 38, 39, 40]],

        [[41, 42, 43, 44, 45],
         [46, 47, 48, 49, 50],
         [51, 52, 53, 54, 55],
         [56, 57, 58, 59, 60]]])
(20, 5, 1) (1, 5, 20)


In [65]:
## 有一些操作只能在連續張量進行，例如：view。故解法為： contiguous()
points.is_contiguous() # check
points_t.is_contiguous()

False

In [67]:
# contiguous() can make a tensor change from non-continuous into a new continuous ones
# content is same but the storage will change
points = torch.tensor([[4.0,1.0],[5.0,3.0],[2.0,1.0]])
print(points)
points_t=points.t()
print(points_t)
print(points_t.storage())

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])
tensor([[4., 5., 2.],
        [1., 3., 1.]])
 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]


In [ ]:
print(points.stride())
print(points_t.stride())
print(points_t.storage())
points_t_cont = points_t.contiguous()
print(points_t_cont)
print(points_t_cont.stride()) #資訊改變stride
print(points_t_cont.storage()) #storage重新排列

(2, 1)
(1, 2)
 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]
tensor([[4., 5., 2.],
        [1., 3., 1.]])
(3, 1)
 4.0
 5.0
 2.0
 1.0
 3.0
 1.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]


## Session 3.9 把張量移到GPU上

In [ ]:
points.stride()

(2, 1)

## Session 3.10 與Numpy的互通性

In [ ]:
# 將tensor(預設32float) 轉乘numpy(預設64float)
import torch
points = torch.ones(3,4)
points_np = points.numpy()
points_np #與 points 共用同一個storage

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)

In [ ]:
points

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
points = torch.from_numpy(points_np) # 將numpy 轉成tensor