# Chap 3 介紹張量(Tensor)

Tensor 是用來表示向量、矩陣或其他維度資料的一種資料結構及容器。
如何得知張量的維度（amount of axis）？ 可尤其索引值的 **個數** 得知。

## Session 3.1 浮點數的世界

## Session 3.2 Tensor: 多維陣列

In [10]:
'''
以下在比較array 跟tensor
'''
a=[1.0,2.0,1.0]
print(a[0])
a[0]=3.0
print(a)

1.0
[3.0, 2.0, 1.0]


In [6]:
import torch
a=torch.ones(3) #創造一個3維的1軸向量，其元素為1
print(a)
print(a[1])
print(float(a[1]))

tensor([1., 1., 1.])
tensor(1.)
1.0


In [7]:
a[2]=2.0
a

tensor([1., 1., 2.])

In [15]:
points=torch.zeros(6)
points[0]=4.0
points[1]=1.0
points[2]=5.0
points[3]=3.0
points[4]=2.0
points[5]=1.0
points

#與以下等價
points2=torch.tensor([4.0,1.0,5.0,3.0,2.0,1.0])
points2

#提取A座標
float(points[0]),float(points[1])

(4.0, 1.0)

In [17]:
## 創造2軸張量
points=torch.tensor([[4.0,1.0],[5.0,3.0],[2.0,1.0]])
points[0]

tensor([4., 1.])

In [ ]:
points.shape
#代表points是一個2軸張量（第0軸有3維，第1軸有2維），.shape用來回傳每個軸的維度

torch.Size([3, 2])

In [20]:
points=torch.zeros(3,2)
points #透過指定shape來建立tensor

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [21]:
#提取2軸tensor的個別元素（by 2 index）
points=torch.tensor([[4.0,1.0],[5.0,3.0],[2.0,1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [22]:
points[0,1]

tensor(1.)

In [ ]:
points[0] #此結果為一個大小為2的1軸張量

tensor([4., 1.])

## Session 3.3 利用索引值操作張量

本節要介紹**範圍式索引法**（用於提取tensor中，一定範圍的元素），類似python list操作方法。<br>
**進階索引**(另一種強大的索引方式)將在chapter4中提到。

In [24]:
some_list =list(range(6)) #產生一個從0到5的數字串列
some_list[:]              #提取串列中所有元素

[0, 1, 2, 3, 4, 5]

In [ ]:
## Python list寫法
some_list[0:4] #提取no.0~no.3個元素
some_list[1:] #提取no.1~最後一個元素
some_list[:4] #提取no.0~no.3個元素
some_list[:-1] #提取no.0~倒數第二個元素
some_list[1:4:2] #提取no.1~no.3個元素，每次間隔2個元素

[1, 3]

In [27]:
## 對tensor使用範圍式索引法
points=torch.tensor([[4.0,1.0],[5.0,3.0],[2.0,1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [28]:
points[1:,:]

tensor([[5., 3.],
        [2., 1.]])

In [29]:
points[1:,0]

tensor([5., 2.])