# Chap 3 介紹張量(Tensor)

Tensor 是用來表示向量、矩陣或其他維度資料的一種資料結構及容器。
如何得知張量的維度（amount of axis）？ 可尤其索引值的 **個數** 得知。

## Session 3.1 浮點數的世界

## Session 3.2 Tensor: 多維陣列

In [10]:
'''
以下在比較array 跟tensor
'''
a=[1.0,2.0,1.0]
print(a[0])
a[0]=3.0
print(a)

1.0
[3.0, 2.0, 1.0]


In [6]:
import torch
a=torch.ones(3) #創造一個3維的1軸向量，其元素為1
print(a)
print(a[1])
print(float(a[1]))

tensor([1., 1., 1.])
tensor(1.)
1.0


In [7]:
a[2]=2.0
a

tensor([1., 1., 2.])

In [15]:
points=torch.zeros(6)
points[0]=4.0
points[1]=1.0
points[2]=5.0
points[3]=3.0
points[4]=2.0
points[5]=1.0
points

#與以下等價
points2=torch.tensor([4.0,1.0,5.0,3.0,2.0,1.0])
points2

#提取A座標
float(points[0]),float(points[1])

(4.0, 1.0)

In [17]:
## 創造2軸張量
points=torch.tensor([[4.0,1.0],[5.0,3.0],[2.0,1.0]])
points[0]

tensor([4., 1.])

In [ ]:
points.shape
#代表points是一個2軸張量（第0軸有3維，第1軸有2維），.shape用來回傳每個軸的維度

torch.Size([3, 2])

In [20]:
points=torch.zeros(3,2)
points #透過指定shape來建立tensor

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [21]:
#提取2軸tensor的個別元素（by 2 index）
points=torch.tensor([[4.0,1.0],[5.0,3.0],[2.0,1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [22]:
points[0,1]

tensor(1.)

In [ ]:
points[0] #此結果為一個大小為2的1軸張量

tensor([4., 1.])

## Session 3.3 利用索引值操作張量

本節要介紹**範圍式索引法**（用於提取tensor中，一定範圍的元素），類似python list操作方法。<br>
**進階索引**(另一種強大的索引方式)將在chapter4中提到。

In [24]:
some_list =list(range(6)) #產生一個從0到5的數字串列
some_list[:]              #提取串列中所有元素

[0, 1, 2, 3, 4, 5]

In [ ]:
## Python list寫法
some_list[0:4] #提取no.0~no.3個元素
some_list[1:] #提取no.1~最後一個元素
some_list[:4] #提取no.0~no.3個元素
some_list[:-1] #提取no.0~倒數第二個元素
some_list[1:4:2] #提取no.1~no.3個元素，每次間隔2個元素

[1, 3]

In [27]:
## 對tensor使用範圍式索引法
points=torch.tensor([[4.0,1.0],[5.0,3.0],[2.0,1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [28]:
points[1:,:]

tensor([[5., 3.],
        [2., 1.]])

In [29]:
points[1:,0]

tensor([5., 2.])

## Session 3.4 為張量命名

利用names參數替每個軸命名（typr: string）

In [ ]:
import torch
weights_named=torch.tensor([0.2126, 0.7152,0.0722], names=["channels"])
weights_named
#refine_names()重設名稱

/var/folders/yb/xnfk9z6x34527z3924bcjqcr0000gn/T/ipykernel_25316/3701717441.py:2: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/c10/core/TensorImpl.h:1974.)
  weights_named=torch.tensor([0.2126, 0.7152,0.0722], names=["channels"])


tensor([0.2126, 0.7152, 0.0722], names=('channels',))

In [3]:
img_t = torch.randn(3,5,5) #創造一個3軸的張量
batch_t = torch.randn(2,3,5,5) #創造一個4軸的張量
img_named = img_t.refine_names(..., 'channels','rows','columns') ## ...表示忽略前面，只幫最後三軸命名
batch_named = batch_t.refine_names(...,'channels','rows','columns')
print("img_named:" , img_t.shape, img_named.names)
print("batch_named:" , batch_t.shape, batch_named.names)

img_named: torch.Size([3, 5, 5]) ('channels', 'rows', 'columns')
batch_named: torch.Size([2, 3, 5, 5]) (None, 'channels', 'rows', 'columns')


In [ ]:
#align_as()將weights_named內tensor的軸按照img_named順序進行排序，（會自動添加缺失的軸）
weights_aligned = weights_named.align_as(img_named) #weights_named為一軸張量
weights_aligned.shape, weights_aligned.names
#weights_aligned


(torch.Size([3, 1, 1]), ('channels', 'rows', 'columns'))

In [8]:
img_named

tensor([[[ 0.7549,  0.7040, -0.5905, -1.4944, -1.1411],
         [ 1.4837, -1.6251, -0.1032, -0.1640,  0.7529],
         [-0.1131, -1.6989, -0.8747, -0.0028,  0.8432],
         [ 0.4779, -0.1079,  0.1461, -1.2731,  0.2933],
         [-0.3215,  0.4853,  1.3529,  1.3185, -1.0132]],

        [[ 1.3211, -0.2918,  1.5793,  0.3865,  0.9758],
         [ 1.0859,  0.0506, -1.6146,  0.9141, -0.7674],
         [-0.5162, -1.6761, -1.5684, -0.2508, -0.4115],
         [-1.4717, -0.5339, -0.6223, -0.0428,  0.2181],
         [-0.6115,  1.6622, -0.1560, -0.6525,  0.9141]],

        [[-0.0164, -0.0712,  0.6364,  0.5131,  0.7174],
         [-0.9668,  0.2966, -0.9905,  0.1763, -0.3980],
         [-0.5453,  0.2671,  0.8572, -0.0907,  1.0738],
         [-1.9566, -0.0190, -0.1056,  1.5258,  0.5857],
         [ 1.6976, -0.5259, -0.7849, -0.4168, -0.2698]]],
       names=('channels', 'rows', 'columns'))

In [9]:
weights_aligned

tensor([[[0.2126]],

        [[0.7152]],

        [[0.0722]]], names=('channels', 'rows', 'columns'))

In [7]:
gray_named = (img_named * weights_aligned).sum("channels")
gray_named.shape, gray_named.names

(torch.Size([5, 5]), ('rows', 'columns'))

In [10]:
gray_named

tensor([[ 1.1042, -0.0642,  1.0499, -0.0042,  0.5071],
        [ 1.0223, -0.2879, -1.2482,  0.6316, -0.4175],
        [-0.4326, -1.5407, -1.2458, -0.1865, -0.0375],
        [-1.0922, -0.4061, -0.4216, -0.1911,  0.2606],
        [-0.3831,  1.2540,  0.1194, -0.2165,  0.4189]],
       names=('rows', 'columns'))

In [ ]:
## 有些函式不支援以張量維度名字來操作，重新命名為none
gray_plain = gray_named.rename(None)
gray_plain.shape, gray_plain.names

(torch.Size([5, 5]), (None, None))