# Chapter 4 用張量表示現實中的資料

## Session 4.1 圖片資料

* 一張圖片資料可以看作一堆**純量的集合**，純量依序排列：高度、寬度的網格當中（也就是像素pixel）。
* 每一個像素可能帶有**單個純量值**，如灰階值。 
* 每一個像素可能帶有**多個純量值**，如不同顏色RGB值；**特徵值**，如景深鏡頭的深度。
* 單個像素值通常會使用**8位元整數**進行編碼（12 or 16為精度更高） <br>
* **img_arr** 是什麼？
>  img_arr為類似numpy arrary的物件<br>
有3個軸：2空間軸（寬高）、1色彩通道軸
* Pytorch 要求圖片資料：C(色彩通道)H(高度)W(寬度)，只要是處理numpy資料後續轉換都很方便！<br> 惟需要注意：<font color=#FF0000>不同軸的排列順序與Pytorch是否吻合</font><br> **解法：**<font color=blue>permute() 函式</font>

* 對資料進行轉換：normalization, rotate, scaling (ch12.6)

In [8]:
import numpy as np
import torch
import imageio
img_arr = imageio.imread("../F1388_Code/data/p1ch4/image-dog/bobby.jpg")
img_arr.shape

#720, 1280為空間大小
#img_arr 為一個3軸張量

/var/folders/yb/xnfk9z6x34527z3924bcjqcr0000gn/T/ipykernel_3916/588946327.py:4: DeprecationWarning: Starting with ImageIO v3 the behavior of this function will switch to that of iio.v3.imread. To keep the current behavior (and make this warning disappear) use `import imageio.v2 as imageio` or call `imageio.v2.imread` directly.
  img_arr = imageio.imread("../F1388_Code/data/p1ch4/image-dog/bobby.jpg")


(720, 1280, 3)

In [10]:
img = torch.from_numpy(img_arr) #先將img_arr轉成pytorch tensor 
out = img.permute(2,0,1)
out.shape

torch.Size([3, 720, 1280])

In [12]:
# 由於需要一次輸入多張照片，在第0軸 插入 Batch 批次軸，使tensor變成 NCHW 的4軸張量
batch_size = 100 
batch = torch.zeros(batch_size, 3, 256, 256, dtype=torch.uint8) #預先建立一個4軸tensor，色彩強度8位元正整數

In [13]:
import os
data_dir = "../F1388_Code/data/p1ch4/image-cats/" #設定圖檔所在資料夾路徑
filenames = [name for name in os.listdir(data_dir) if os.path.splitext(name)[-1] == ".png"]

for i, filename in enumerate(filenames):
    img_arr = imageio.imread(os.path.join(data_dir, filename))
    img_t = torch.from_numpy(img_arr)
    img_t = img_t.permute(2,0,1) # 調整tensor中各軸排列順序
    img_t = img_t[:3] #有些圖片會有表示透明度的第3軸，是我們不需要的，故只保留前面3軸

    batch[i] = img_t

batch.shape

/var/folders/yb/xnfk9z6x34527z3924bcjqcr0000gn/T/ipykernel_3916/1620507834.py:6: DeprecationWarning: Starting with ImageIO v3 the behavior of this function will switch to that of iio.v3.imread. To keep the current behavior (and make this warning disappear) use `import imageio.v2 as imageio` or call `imageio.v2.imread` directly.
  img_arr = imageio.imread(os.path.join(data_dir, filename))


torch.Size([100, 3, 256, 256])

In [15]:
# 將像素值左normalization
# method 1
batch = batch.float()
batch /= 255.0
# method 2 standarlization

n_channels = batch.shape[1]  #取得色彩通道的數量

for c in range(n_channels): #依序走訪每個色彩通道
    mean = torch.mean(batch[:,c])
    std = torch.std(batch[:,c])
    batch[:,c] = (batch[:,c] - mean)/std

## Session 4.2 3D立體圖片資料

In [4]:
import imageio
import torch
dir_path = "../F1388_Code/data/p1ch4/volumetric-dicom/2-LUNG 3.0  B70f-04083"
vol_arr =imageio.volread(dir_path, 'DICOM')
vol_arr.shape

#(99, 512, 512)通道軸被省略掉了 
#99 張數
#512 512 為尺寸

Reading DICOM (examining files): 1/99 files (1.0%99/99 files (100.0%)
  Found 1 correct series.
Reading DICOM (loading data): 99/99  (100.0%)


(99, 512, 512)

In [6]:
# Pytorch要求個軸排列順序 N x C x H x W
vol = torch.from_numpy(vol_arr).float() #先把資料轉成浮點數張量
vol = torch.unsqueeze(vol, 1 ) #在第2軸位置增加插入一個通道軸，dim=1
vol = torch.unsqueeze(vol, 2 ) #在第3軸位置增加插入一個深度軸，dim=1
vol.shape

torch.Size([99, 1, 1, 512, 512])

## Session 4.3 表格資料

- Tensor in Pytorch: 所有資料只能為同一種數值類型（float, int or boolin），需先行做轉換
- 不同資料資料類別處理、詮釋原則：
    - *Continuous* 有明確的大小關係，也可用比例關係呈現。（註：**時間**是一種區間關係，無比例關係）
    - *Ordinal* 有明確的大小關係，但區間間隔**未必**為固定尺度，不能對他們進行數學計算。
    - *Categorical* 無法排序也無數值關聯性，只是**利用不同值進行區分**。
- 載入csv的幾個選項：python中的**csv模組**、**numpy**(首選；與PyTorch互通性最佳)、**pandas**(最省記憶體與時間)。
- 想將目標張量作為訓練時的類別標籤
    - method 1: 當純視為整數相量 code: floatXX.long() <br>
    - method 2: 將字串指派為整數 one-hot encoding ，離散型適用此方法 code: scatter_()
     <br>**來源張量的軸數，必須與scatter 到的結果張量相同**
- pytorch 標準化公式：data_normalized = (data-data_mean)/ torch.sqrt(data_var)
- **進階索引**
- 利用直覺分類可能過於簡化，接下來的章節會利用**神經網路**來解決分類問題。


In [ ]:
import torch
import csv
import numpy as np
dir_path = "../F1388_Code/data/p1ch4/tabular-wine/winequality-white.csv"
wineq_numpy = np.loadtxt(dir_path, dtype=np.float32, delimiter=";",skiprows=1)
                                                     #利用分號對資料進行分割 ＃跳過標題列
wineq_numpy

#檢查資料是否完整
col_list = next(csv.reader(open(dir_path),delimiter=";"))
wineq_numpy.shape, col_list

((4898, 12),
 ['fixed acidity',
  'volatile acidity',
  'citric acid',
  'residual sugar',
  'chlorides',
  'free sulfur dioxide',
  'total sulfur dioxide',
  'density',
  'pH',
  'sulphates',
  'alcohol',
  'quality'])

In [6]:
wineq =torch.from_numpy(wineq_numpy)
wineq.shape, wineq.dtype

(torch.Size([4898, 12]), torch.float32)

In [ ]:
data = wineq[:,:-1]
data, data.shape

(tensor([[ 7.0000,  0.2700,  0.3600,  ...,  3.0000,  0.4500,  8.8000],
         [ 6.3000,  0.3000,  0.3400,  ...,  3.3000,  0.4900,  9.5000],
         [ 8.1000,  0.2800,  0.4000,  ...,  3.2600,  0.4400, 10.1000],
         ...,
         [ 6.5000,  0.2400,  0.1900,  ...,  2.9900,  0.4600,  9.4000],
         [ 5.5000,  0.2900,  0.3000,  ...,  3.3400,  0.3800, 12.8000],
         [ 6.0000,  0.2100,  0.3800,  ...,  3.2600,  0.3200, 11.8000]]),
 torch.Size([4898, 11]))

In [10]:
target = wineq[:,-1]
print(target, target.shape)
target = wineq[:,-1].long()
print(target)

tensor([6., 6., 6.,  ..., 6., 7., 6.]) torch.Size([4898])
tensor([6, 6, 6,  ..., 6, 7, 6])


In [ ]:
target_onehot = torch.zeros(target.shape[0],10) #建立shape為[4898,10]值均為0的tensor，用來存放encoding結果
a = target_onehot.scatter_(1, target.unsqueeze(1),1.0) 
             # 第一個參數 1 (dim)： 指定操作的維度(第1軸)。dim=1 表示我們要沿著**橫軸（columns）**填入數值。
             # unsqueeze(1) 會在第 1 維（行）增加一個維度，將形狀變成 (Batch_Size, 1)
             # 這是要填入的數值
a, a.shape

(tensor([[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 1., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]]),
 torch.Size([4898, 10]))

In [13]:
target_onehot, target_onehot.shape

(tensor([[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 1., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]]),
 torch.Size([4898, 10]))

In [15]:
target_unsqueezed = target.unsqueeze(1) #添加一個軸至第一軸
print(target.shape, target_unsqueezed, target_unsqueezed.shape)

torch.Size([4898]) tensor([[6],
        [6],
        [6],
        ...,
        [6],
        [7],
        [6]]) torch.Size([4898, 1])


In [19]:
data_mean = torch.mean(data, dim=0)
print(data_mean)

data_var = torch.var(data, dim=0)
print(data_var)

data_normalized = (data-data_mean)/ torch.sqrt(data_var)
print(data_normalized)

tensor([6.8548e+00, 2.7824e-01, 3.3419e-01, 6.3914e+00, 4.5772e-02, 3.5308e+01,
        1.3836e+02, 9.9403e-01, 3.1883e+00, 4.8985e-01, 1.0514e+01])
tensor([7.1211e-01, 1.0160e-02, 1.4646e-02, 2.5726e+01, 4.7733e-04, 2.8924e+02,
        1.8061e+03, 8.9455e-06, 2.2801e-02, 1.3025e-02, 1.5144e+00])
tensor([[ 1.7208e-01, -8.1761e-02,  2.1326e-01,  ..., -1.2468e+00,
         -3.4915e-01, -1.3930e+00],
        [-6.5743e-01,  2.1587e-01,  4.7996e-02,  ...,  7.3995e-01,
          1.3422e-03, -8.2419e-01],
        [ 1.4756e+00,  1.7450e-02,  5.4378e-01,  ...,  4.7505e-01,
         -4.3677e-01, -3.3663e-01],
        ...,
        [-4.2043e-01, -3.7940e-01, -1.1915e+00,  ..., -1.3130e+00,
         -2.6153e-01, -9.0545e-01],
        [-1.6054e+00,  1.1666e-01, -2.8253e-01,  ...,  1.0049e+00,
         -9.6251e-01,  1.8574e+00],
        [-1.0129e+00, -6.7703e-01,  3.7852e-01,  ...,  4.7505e-01,
         -1.4882e+00,  1.0448e+00]])


In [16]:
data

tensor([[ 7.0000,  0.2700,  0.3600,  ...,  3.0000,  0.4500,  8.8000],
        [ 6.3000,  0.3000,  0.3400,  ...,  3.3000,  0.4900,  9.5000],
        [ 8.1000,  0.2800,  0.4000,  ...,  3.2600,  0.4400, 10.1000],
        ...,
        [ 6.5000,  0.2400,  0.1900,  ...,  2.9900,  0.4600,  9.4000],
        [ 5.5000,  0.2900,  0.3000,  ...,  3.3400,  0.3800, 12.8000],
        [ 6.0000,  0.2100,  0.3800,  ...,  3.2600,  0.3200, 11.8000]])

### 4.3.6 進階索引

In [22]:
bad_indexes = target <=3
print(bad_indexes.shape, bad_indexes.dtype, bad_indexes.sum())

bad_data = data[bad_indexes]
print(bad_data.shape)

torch.Size([4898]) torch.bool tensor(20)
torch.Size([20, 11])


In [24]:
## 進階索引補充
a = torch.arange(10) #創建一個0-9的1軸向量
print(a)

b = a>= 5
print(b)

a[b]

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([False, False, False, False, False,  True,  True,  True,  True,  True])


tensor([5, 6, 7, 8, 9])

In [ ]:
bad_data = data[target <=3]
mid_data= data[(target >3) & (target <7)]
good_data= data[target >=7]

bad_mean = torch.mean(bad_data, dim=0)
mid_mean = torch.mean(mid_data, dim=0)
good_mean = torch.mean(good_data, dim=0)

# zip 會把多個 list（或 tensor）的第 k 個元素抓出來，組合成一個 Tuple
# enumerate 的作用是為你的資料加上索引編號 (Index)
for i, args in enumerate(zip(col_list, bad_mean, mid_mean, good_mean)):
    print('{:2} {:20} {:6.2f} {:6.2f} {:6.2f}'.format(i, *args)) #* 在這裡叫做 Unpacking Operator (解包運算子)

 0 fixed acidity          7.60   6.89   6.73
 1 volatile acidity       0.33   0.28   0.27
 2 citric acid            0.34   0.34   0.33
 3 residual sugar         6.39   6.71   5.26
 4 chlorides              0.05   0.05   0.04
 5 free sulfur dioxide   53.33  35.42  34.55
 6 total sulfur dioxide 170.60 141.83 125.25
 7 density                0.99   0.99   0.99
 8 pH                     3.19   3.18   3.22
 9 sulphates              0.47   0.49   0.50
10 alcohol               10.34  10.26  11.42


In [30]:
## 想利用 total sulfur dioxide 來分類酒類的好壞與否
total_sulfur_threshold = 141.83
total_sulfur_data = data[:,6] #取出總二氧化硫量資訊
                        #lt()可以挑出A中，值小於B的項目索引
                        #.  A                  B
predicted_indexs = torch.lt(total_sulfur_data, total_sulfur_threshold)
print(predicted_indexs.shape, predicted_indexs.dtype, predicted_indexs.sum())

# 檢查實際標標籤分類情況
actual_indexes = target > 5
print(actual_indexes.shape, actual_indexes.dtype, actual_indexes.sum())

torch.Size([4898]) torch.bool tensor(2727)
torch.Size([4898]) torch.bool tensor(3258)


In [ ]:
## 確認吻合程度
n_matches = torch.sum(predicted_indexs & actual_indexes).item() #找尋兩者都為true，透過.item()計算結果吻合項目數目
n_predicted = torch.sum(predicted_indexs).item()
n_actual = torch.sum(actual_indexes).item()
n_matches, n_matches/ n_predicted, n_matches/ n_actual
           #預測中好酒比例           #實際好酒中我們實際預測出的比例

#這方法效果有待改進，所以接著我們會利用神經網路來解決這問題 

(torch.Size([4898]), torch.bool, tensor(3258))