# Session 5.3 以降低損失為目標

- Square Error Loss function 對有明顯誤差的預測像有較強的懲罰作用。
- Broadcasting 張量擴張

In [1]:
import torch

t_c = [0.5,  14.0, 15.0, 28.0, 11.0,  8.0,  3.0, -4.0,  6.0, 13.0, 21.0] #攝氏溫度
t_u = [35.7, 55.9, 58.2, 81.9, 56.3, 48.9, 33.9, 21.8, 48.4, 60.4, 68.4] #溫度計上對應到的讀數
t_c = torch.tensor(t_c)
t_u = torch.tensor(t_u)

In [2]:
def model(t_u, w, b):
    return w * t_u +b

def loss_fn(t_p, t_c): #定義損失函數
    squared_diffs = (t_p - t_c)**2
    return squared_diffs.mean()

w = torch.ones(())
b = torch.zeros(())
t_p = model(t_u, w, b)
t_p

tensor([35.7000, 55.9000, 58.2000, 81.9000, 56.3000, 48.9000, 33.9000, 21.8000,
        48.4000, 60.4000, 68.4000])

In [3]:
loss = loss_fn(t_p, t_c)
loss

tensor(1763.8846)

In [4]:
x = torch.ones(()) #0軸
y = torch.ones((3,1)) #2軸 3x1
z = torch.ones((1,3)) #2軸 1x3
a = torch.ones((2,1,1)) #3軸 2x1x1

print(f"shapes: x:{x.shape}, y:{y.shape}")
print(f"shapes: z:{x.shape}, a:{y.shape}")
print("x * y:" ,(x*y).shape)
print("y * z:" ,(y*z).shape)
print("y * z * a:" ,(y*z*a).shape)

shapes: x:torch.Size([]), y:torch.Size([3, 1])
shapes: z:torch.Size([]), a:torch.Size([3, 1])
x * y: torch.Size([3, 1])
y * z: torch.Size([3, 3])
y * z * a: torch.Size([2, 3, 3])


In [7]:
y*z

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [8]:
a

tensor([[[1.]],

        [[1.]]])